version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
    - "5002:5002"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - webapp
  webapp:
    build: .
    expose:
      - "5002"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: my-redis
    volumes:
    - redis-data:/data
    ports:
    - "6379:6379"  
    environment: 
    - REDIS_HOST=redis
    - REDIS_PORT=6379
volumes:
  redis-data: 
